package spr.dao;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import spr.bean.Test1Criteria;
import spr.bean.Test1Entity;

import java.util.List;
@Component
public interface Test1Dao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    long countByExample(Test1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    int deleteByExample(Test1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    int insert(Test1Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    int insertSelective(Test1Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    List<Test1Entity> selectByExample(Test1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    Test1Entity selectByPrimaryKey(Integer id1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") Test1Entity record, @Param("example") Test1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    int updateByExample(@Param("record") Test1Entity record, @Param("example") Test1Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    int updateByPrimaryKeySelective(Test1Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    int updateByPrimaryKey(Test1Entity record);
}