package spr.dao2;

import org.apache.ibatis.annotations.Param;
import spr.bean.Test2Criteria;
import spr.bean.Test2Entity;

import java.util.List;

public interface Test2Dao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    long countByExample(Test2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    int deleteByExample(Test2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    int deleteByPrimaryKey(Integer id2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    int insert(Test2Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    int insertSelective(Test2Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    List<Test2Entity> selectByExample(Test2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    Test2Entity selectByPrimaryKey(Integer id2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") Test2Entity record, @Param("example") Test2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    int updateByExample(@Param("record") Test2Entity record, @Param("example") Test2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    int updateByPrimaryKeySelective(Test2Entity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    int updateByPrimaryKey(Test2Entity record);
}