package spr.bean;

public class Test2Entity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * 
     * This field corresponds to the database column test2.id2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    private Integer id2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * 
     * This field corresponds to the database column test2.name2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    private String name2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test2.id2
     *
     * @return the value of test2.id2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    public Integer getId2() {
        return id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test2.id2
     *
     * @param id2 the value for test2.id2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    public void setId2(Integer id2) {
        this.id2 = id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test2.name2
     *
     * @return the value of test2.name2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test2.name2
     *
     * @param name2 the value for test2.name2
     *
     * @mbg.generated Wed Dec 14 15:28:46 CST 2016
     */
    public void setName2(String name2) {
        this.name2 = name2 == null ? null : name2.trim();
    }
}