package spr.bean;

public class Test1Entity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * 
     * This field corresponds to the database column test1.id1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    private Integer id1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * 
     * This field corresponds to the database column test1.name1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    private String name1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.id1
     *
     * @return the value of test1.id1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    public Integer getId1() {
        return id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test1.id1
     *
     * @param id1 the value for test1.id1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    public void setId1(Integer id1) {
        this.id1 = id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.name1
     *
     * @return the value of test1.name1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    public String getName1() {
        return name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test1.name1
     *
     * @param name1 the value for test1.name1
     *
     * @mbg.generated Wed Dec 14 14:36:55 CST 2016
     */
    public void setName1(String name1) {
        this.name1 = name1 == null ? null : name1.trim();
    }
}